apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: my-cluster-11
  namespace: old-namespace 
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 1
  users:
    zalando:  # database owner
    - superuser
    - createdb
    akshat:
    - superuser
    - createdb
  databases:
    foo: zalando  # dbname: owner
    fire: akshat
  preparedDatabases:
    bar: {}
  postgresql:
    version: "14"
